# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MindValley' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MindValley
  pod 'RealmSwift'
  pod 'Kingfisher'

  target 'MindValleyTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RealmSwift'
    pod 'Kingfisher'
  end

end
